version: '3.8'

services:
  
  app:
    container_name: flask-app
    image: flask-app:latest
    restart: always

  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"


